### ISSUE TITLE
Kubernetes (k8s) Monitoring and Troubleshooting Support: Logs and metadata collection and visualization

### ISSUE THREAD

**Issue by mchene** [splunk/docker-itmonitoring#15]
Add support for the following:
a. collect logs as daemonset using the Splunk Universal Forwarder (UF)
b. Collect k8s metadata using the Splunk UF as a Deployment type from the k8s API Server
c. Sample app with dashboards that correlate logs, meta data and metrics about the health of the k8s cluster

**Comment by matthewmodestino** [comment]
Pull #16 submitted

**Comment by matthewmodestino** [comment]
demo merged into master. closing issue
