### ISSUE TITLE
Why is this not available on Splunkbase?

### ISSUE THREAD

**Issue by ChrisYounger** [splunk/docker-itmonitoring#26]
I have a small amount of Docker containers that I need to monitor and trying to decode and understand the documentation of all this stuff is way harder than it needs to be. Is this an abandoned project? 

When I do finally figure this out, can I take some of the code from this repo and package it up with documentation for release on Splunkbase?

**Comment by halr9000** [comment]
Hi Chris. I can't speak for PM, but this app has not been touched in some time. Rest assured that the container monitoring use cases are still important to us...

@mikedickey did you want to add anything?

**Comment by mikedickey** [comment]
@dbaldwin-splunk would be best person from PM to comment, but I believe this has been replaced by Splunk Connect for Kubernetes https://github.com/splunk/splunk-connect-for-kubernetes

**Comment by matthewmodestino** [comment]
Hey Chris, 

This was a repo that myself and a few former Splunk colleagues worked on over the years as we began experimenting into the container world. 

Since then we have released various collection methods and are working on apps to use the data. 

What specific part of this repo are you interested in? Perhaps I can steer you to more up to date and supported items.

**Comment by ChrisYounger** [comment]
Hi Matthew,

I was wanting to monitor a very small docker environment.  I have since rewritten and packaged up the parts I needed from TA-dockerstats and I have also released it on Splunkbase here: 
 https://splunkbase.splunk.com/apps/#/author/chrisyoungerjds

This has solved my problem now.  

I am happy to update my Splunkbase pages to point to more official guidance of how to monitor docker if someone can tell me.

**Comment by halr9000** [comment]
Great work @ChrisYounger ! Hey, watch the Splunk blog for the next Splunktrust nomination period. This is exactly the kind of community engagement we like to reward. :)
